version: "3"
services:
    mysql:
        image: mysql:5.7
        container_name: mysql
        ports:
          - "3306:3306"
        volumes:
          - /data/var/lib/mysql:/var/lib/mysql
          - /data/var/etc/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
        environment:
          MYSQL_ROOT_PASSWORD: 123456
        networks:
          - lnmp
        restart: always
    nginx:
        image: nginx:1.14-alpine
        container_name: nginx
        depends_on:
          - php-fpm
          - mysql
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - /data/var/www:/usr/share/nginx/html
          - /data/var/etc/nginx/conf.d:/etc/nginx/conf.d
          - /data/var/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
          - /data/var/log/nginx:/var/log/nginx
        links:
          - php-fpm
        networks:
          - lnmp
        restart: always
    php-fpm:
        build: ./app/php
        image: php-fpm:7.2
        container_name: php-fpm
        ports:
            - "9000:9000"
        volumes:
            - /data/var/www:/var/www/html
            - /data/var/etc/php:/usr/local/etc/php/conf.d
        networks:
            - lnmp
        restart: always
    redis:
        build: ./app/redis
        image: redis:3.2
        container_name: redis
        ports:
            - "6379:6379"
        volumes:
            - /data/var/lib/redis:/data
            - /data/var/etc/redis/redis.conf:/etc/redis.conf
        networks:
            - lnmp
        restart: always
networks:
  lnmp:
    driver: bridge
