version: "3"
services:
    mysql:
        image: mysql:5.7
        container_name: mysql
        ports:
          - "3306:3306"
        volumes:
          - /data/var/lib/mysql:/var/lib/mysql
          - /data/var/log/mysql:/var/log/mysql
          - /data/var/etc/mysql:/etc/mysql/
        environment:
          MYSQL_ROOT_PASSWORD: 123456
        networks:
          - mysql
        restart: always
    nginx:
        image: nginx:1.14
        container_name: nginx
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - /data/var/www:/usr/share/nginx/html
          - /data/var/etc/nginx/conf.d:/etc/nginx/conf.d
          - /data/var/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
          - /data/var/log/nginx:/var/log/nginx
        networks:
            - nginx
        restart: always

networks:
  mysql:
  nginx:
